### PR TITLE
Check box functions

### PR DESCRIPTION
**Pull request by kulksoh21**
This week I am to build off of the checkbox I created last week and work on ways to display things off of it. That is exactly what I have done however, I intend on improving on it this week. I just wanted to create the initial pull request.

### CODE REVIEW

**Review by AryanMashruwala — CHANGES_REQUESTED** [review]
This needs to be developed much further. Seems like the checkbox can display the image, but this isn't fully integrated with the rewards system. On top of that, there need to be test cases to verify that this handles many inputs.

**Comment by Dhirajk1** [comment]
Um, you usually don't make pull requests with no intention of having the current code merged...

**Comment by kulksoh21** [comment]
The functionality of the checkbox is now updated to handle displaying images. The code checks to see if the checkbox is clicked on and if it is, it displays an image. This is done for the rewards system and intends on merging with frontendk to avoid cluttering the UI. Test case is written to check if the image gets displayed.

**Comment by Dhirajk1** [comment]
Looks solid

**Review by Dhirajk1 — APPROVED** [review]
Coolio

**Review by AryanMashruwala — APPROVED** [review]
Looks good, thank you for going over the requested changes.

**Pull request merged**
